Feature/idcom 1988 did sol support explorer
identity-com/solana pull request #328
Opened 2022-06-16 15:53 UTC by frank-haomeng-wang

#### Summary of Changes: I add more features to the sol explorer and specifically add more features to the sol-did detail card and account detail card.

2022-06-17 15:12 UTC, rado0x54 requested changes
Please extract the duplicate display code (and other's that might be related) into one higher class / utility.

2022-06-17 15:12 UTC, rado0x54 commented on explorer/src/components/account/SolDidAccountSection.tsx
> +function display(value: any): JSX.Element {
Why is the code here different to the one in the instruction one? Ideally for the presentation element of SolData this uses the same code for both components.

2022-06-17 15:12 UTC, rado0x54 commented on explorer/src/providers/accounts/index.tsx
> +  const parsedData = SolData.decode<SolData>(result.data);
Ah ok, this function does the mapping between SolData and DidSolProgramData. It's quite the overhead, but I guess it's needed to have a clean data-model separation.

2022-06-18 00:20 UTC, frank-haomeng-wang commented
I have made the cases more specific in sol did account section and also optimize the logic of the structure.
<img width="1037" alt="Screen Shot 2022-06-17 at 5 06 32 PM" src="https://user-images.githubusercontent.com/70120564/174414675-480a7a78-5d25-4ffa-806c-c6fe97638420.png">
<img width="2" alt="Screen Shot 2022-06-17 at 11 33 14 AM" src="https://user-images.githubusercontent.com/70120564/174414718-cddf7086-5b4d-406c-a9a8-5379cf83fa73.png">

2022-06-21 20:11 UTC, closed without merging